server:
  port: 8084

spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:   #这里只是接收消息而不发送，所以不用配置template相关内容。
    host: 192.168.41.76
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 30  #10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}
ly:
  page:
    filePath: C:/develop/nginx-1.12.2/html/item
